### ISSUE TITLE
[BUG] bad shortcut

### ISSUE THREAD

**Issue by Wjxfi** [deltazefiro/Amarok-Hider#22] opened 2023-01-19 19:21 UTC
**Describe the bug / 问题描述**
请清晰地描述您遇到的异常。
the shortcut behaves very strangely. It doesn't work for a while, with multiple clicks, and then shows the wrong color. When the shortcut is blue, something must be on. Here on the contrary, it is off. This is not right.

**Screenshots / 截图**
（可选）问题复现时候的截图或录屏。
https://user-images.githubusercontent.com/113500363/213538443-5457a71c-3f38-4fbd-84e9-8e90f3c679d7.mp4

**To Reproduce / 复现步骤**
Steps to reproduce the behavior / 复现异常的步骤:
1. click on shortcut

**Expected behavior / 预期行为**
描述您认为正常情况下应该发生什么。
works correctly from the first click. When file hiding is on, the shortcut turns blue.

**Basic Information: / 请填写以下信息:**
 - OS (ROM) / 系统:
miui 12.0.6
 - Android Version / 安卓版本: [e.g. 12]
androis 12
 - Amarok Version / Amarok版本: [e.g. v0.8.1b1-foss]
0.8.2a3

**Comment by deltazefiro** [comment] 2023-01-20 00:43
Uh yes, that's a known bug. Hard to fix.

**Comment by deltazefiro** [comment] 2023-01-31 15:06
Done! Give [this](https://mega.nz/file/De4lgAwI#oTRdihCk-ly8-LOocwEAo3VhbIS92_GiLxck-HxcE0c) a try.

**Comment by deltazefiro** [comment] 2023-01-31 23:33
May related to MIUI's battery saving strategy.
Go to system setting, search Manage Apps, Amarok > Battery saver > switch to No restrictions.

**Comment by deltazefiro** [comment] 2023-02-01 06:22
> shortcut now works very well but the problem is the color. It's blue when it's off

It works as is. The shortcut should be "Active" (or blue) when Amarok is **not** in the hidden state - it is kinda counterintuitive but I'd like to keep it "Inactive" (grey) at most of the time, which is the hidden state.

> the problem is in the first click on the shortcut. On my first click it does not turn blue, but it said hidden

WIP.

**Comment by deltazefiro** [comment] 2023-02-02 15:10
> application is not installed (error)

Uninstall the old version Amarok and try again.

**Comment by deltazefiro** [comment] 2023-02-02 23:16
> it turned blue for a second and then went back to normal

🤔 Could you provide a new screen recording?

**Comment by deltazefiro** [comment] 2023-02-03 05:37
Weird. I'm using almost the same environment you are using - MIUI & Android 12. I cannot reproduce this issue.

**Comment by deltazefiro** [comment] 2023-02-03 05:52
> > Weird. I'm using almost the same environment you are using - MIUI & Android 12. I cannot reproduce this issue.
> 
> it happens after installing the application, once

Cannot reproduce either. And I noticed that your icon label did not turn into "Processing" as expected (ref the video above), right?

**Comment by deltazefiro** [comment] 2023-02-04 03:18
Um... Tried on several more devices. Failed not reproduce. :disappointed: 
Well, yeah maybe the issue only happens on few devices - and as it just happens once and has no severe consequences, I think maybe we can just let it go.
I'll place the previous fix in next release and see if anyone else encountered the same issue.

**Comment by deltazefiro** [comment] 2023-02-04 08:13
It's no bother at all! Thanks for reporting the issue and for your support. :heart:
Let's close the issue now. As always, feel free to open a new issue (or ask me to reopen this one) if you find a way to reproduce it!

**Closed by deltazefiro** 2023-02-04 08:13 UTC
Labels: bug
